### PR TITLE
Fix the issues found in standard version 2023c

### PR DESCRIPTION
**Pull request by celeron533**
The solution may not perfect.
- Fix 'Photoacoustic Excitation Characteristics Attributes' key not found issue
- Fix 'Photoacoustic Reconstruction Algorithm Attributes' not found issue #93

Pre-request to generate success build: PR #83

### CODE REVIEW

**Comment by johndgiese** [comment]
@russellkan can you review this PR for correctness, completeness, etc. when you have a chance? I think you'll need to manually merge it once it's in good shape.

**Comment by mkzia** [comment]
I am still getting the following error with branch 2023c_new

PYTHONPATH=.. python3 extract_conf_profile_attributes.py tmp/part15.html dist/attributes.json > dist/confidentiality_profile_attributes.json
Traceback (most recent call last):
  File "/Users/blah/github/dicom-standard/dicom_standard/extract_conf_profile_attributes.py", line 61, in <module>
    verify_table_integrity(parsed_table_data, cast(AttrTableType, attributes))
  File "/Users/blah/github/dicom-standard/dicom_standard/extract_conf_profile_attributes.py", line 53, in verify_table_integrity
    raise Exception(error_msg)
Exception: One or more attributes in tables 6-1 and E.1-1 have inconsistent properties between tables:
Attribute "Referenced Patient Alias Sequence" (0038,0004) is retired in Table 6-1 but not in Table E.1-1.
make: *** [dist/confidentiality_profile_attributes.json] Error 1
make: *** Deleting file `dist/confidentiality_profile_attributes.json'

**Comment by celeron533** [comment]
> @celeron533 I am still getting the following error with branch 2023c_new
> 
> File "/Users/blah/github/dicom-standard/dicom_standard/extract_conf_profile_attributes.py", line 53, in verify_table_integrity raise Exception(error_msg) Exception: One or more attributes in tables 6-1 and E.1-1 have inconsistent properties between tables: Attribute "Referenced Patient Alias Sequence" (0038,0004) is retired in Table 6-1 but not in Table E.1-1. make: *** [dist/confidentiality_profile_attributes.json] Error 1 make: *** Deleting file `dist/confidentiality_profile_attributes.json'

Hello @mkzia , this PR requires #83 to be merged to your working branch first.

**Comment by russellkan** [comment]
@mkzia good catch. The workaround in #83 is actually for a different issue that is fixed in 2023e.

@dclunie Should the `Referenced Patient Alias Sequence` attribute be retired or not? The current (2023e) [Table 6-1](https://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_6.html#para_74d743fc-e532-4817-8477-58d1e9a8de57) suggests that it was retired as of 2023d, though that version doesn't have it retired in either [Table 6-1](https://dicom.nema.org/medical/dicom/2023d/output/chtml/part06/chapter_6.html#para_74d743fc-e532-4817-8477-58d1e9a8de57) nor [Table E.1-1](https://dicom.nema.org/medical/dicom/2023d/output/html/part15.html#para_26d0b4be-9dae-4b57-ab18-8e524dde7dc1).

**Review by russellkan — APPROVED** [review]
Looks good to me. If you have a chance, could you add unit tests for these workarounds?

Something like
```
def test_extra_words_in_table_a_89_4_1(part03):
    rows = get_table_rows_from_ids(part03, ['table_A.89.4-1'], col_titles=['functional_group_macro'])
    macro_name = 'Photoacoustic Reconstruction Algorithm'
    row = next(filter(lambda r: macro_name in r['functional_group_macro'], rows))
    assert 'Macro Attributes' in row['functional_group_macro'], 'Row no longer contains extra "Macro Attributes"'
```

**Comment by russellkan** [comment]
Update: seems like the current version (2023e) has fixed one of the issues:
>Macro table 'Photoacoustic Excitation Characteristics Attributes' is not using suffix 'Macro Attributes'

See [table](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.34.5.html#table_C.8.34.5.1-1):
image

This workaround can be removed!

**Comment by dclunie** [comment]
@russellkan, yes, the `Referenced Patient Alias Sequence` data element was retired by CP 2281, which was applied to 2023d to make 2023e, and it should indeed be retired in PS3.15 as well - I will fix that editorially in the upcoming 2024a. Note that the edition listed for retired data elements in PS3.6 is the edition in which the data element [last appeared before it was retired](https://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_5.html#para_de76b9f8-43dd-479f-80de-478177413dd9).

**Comment by celeron533** [comment]
Tested 2024a with [8478e17](https://github.com/innolitics/dicom-standard/commit/8478e1797b54550a985d9e9420a46f38ba9d6ca6) , all good. Close this PR.

**Pull request closed without merging**
